import React from "react";
import Link from "next/link";
import Head from "next/head";

export default function Layout({ title, children }) {
  return (
    <>
      <style jsx>
        {`
          .custom-text-title:before {
            content: "";
            position: absolute;
            bottom: -5px;
            left: 0;
            width: 50px;
            height: 2px;
            background: #f00;
          }

          footer .custom-text-title {
            display: inline-block;
            font-size: 1.5em;
            position: relative;
            margin-block-start: 0.83em;
            margin-block-end: 0.83em;
            margin-inline-start: 0px;
            margin-inline-end: 0px;
            font-weight: 500;
            margin-bottom: 15px;
          }
        `}
      </style>
      <Head>
        <title>{title ? `${title} | Cabsfour SSS` : "Cabsfour SSS"}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='flex min-h-screen flex-col justify-between'>
        <header>
          <nav className='flex h-12 items-center px-4 justify-between shadow-md'>
            <Link href='/' className='p-2'>
              Cabsfour SSS
            </Link>
            <div>
              <Link href='/cart' className='p-2'>
                Cart
              </Link>
              <Link href='/login' className='p-2'>
                Login
              </Link>
            </div>
          </nav>
        </header>
        <main className='container m-auto mt-4 px-4'>{children}</main>
        <footer>
          <div className='flex flex-wrap justify-between px-20 pt-8 bg-[#111111] text-white'>
            <div className='w-full lg:w-1/3'>
              <div className='custom-text-title'>About Us</div>
              <p className='text-[#999999]'>
                Cabsfour Security Systems Services is a Filipino owned company
                formed by dedicated entrepreneurs more than two Decades work
                experience in electronic security system integration. We are
                engaged in integrating various Electronic Security products such
                as Business Security System, Biometrics Access Controls, FDAS,
                IPBX, Electric Fence, Structured Cabling, Solar System Public
                Address System, Electrical, Alarm and CCTV.
              </p>
            </div>
            <div className='w-full lg:w-1/5 mt-5 lg:mt-0'>
              <span className='custom-text-title'>Quick Links</span>
              <ul className='text-[#999999]'>
                <li>
                  <a href='about.html'>About Us</a>
                </li>
                <li>
                  <a href='Services.html'>Services</a>
                </li>
                <li>
                  <a href='Projects.html'>Projects</a>
                </li>
                <li>
                  <a href='Products.html'>Products</a>
                </li>
                <li>
                  <a href='Contact Us.html'>Contact Us</a>
                </li>
                <li>
                  <a href='Account.html'>Account</a>
                </li>
              </ul>
            </div>
            <div className='w-full lg:w-1/3 my-5 lg:mt-0'>
              <span className='custom-text-title'>Contact Info</span>
              <ul className='text-[#999999]'>
                <li>
                  <i className='fas fa-map-marker-alt'></i> #067 Overland Subd
                  Bagac, 2107 Bataan, Philippines
                </li>
                <li>
                  <i className='fas fa-phone'></i> +63 9754918698
                </li>
                <li>
                  <i className='fas fa-envelope'></i>
                  <a href='mailto:cabantacet@gmail.com'>cabantacet@gmail.com</a>
                </li>
              </ul>
            </div>
          </div>
          <div className='w-full bg-[#181818] text-white text-center p-2'>
            Copyright 2022. All Rights Reserved{" "}
          </div>
        </footer>
      </div>
    </>
  );
}
